// This file is generated by Slice Machine. Update with care!

import BlogContent from './BlogContent';
import NavLink from './NavLink';

export {
	BlogContent,
	NavLink,
};

export const components = {
	blog_content: BlogContent,
	nav_link: NavLink,
};
